php_apache:
  image: webdevops/php-apache:7.1
  links:
    - db:mysql
    - elasticsearch:elastic
  ports:
    - 5555:80
  volumes:
    - ./:/app/
    - ./config/php/php.ini/:/opt/docker/etc/php/php.ini
db:
  image: mariadb
  ports:
    - 3307:3306
  volumes:
    - "./data/:/var/lib/mysql"
  environment: 
    MYSQL_ROOT_PASSWORD: examplepass

elasticsearch:
  image: elasticsearch:latest
  restart: always
  environment:
    ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  ports:
    - "9200:9200"
  volumes:
    - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"